# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-23 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_followergroup_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='group',
        ),
    ]
